services:
  - type: web
    name: gym-management-api
    env: dotnet
    buildCommand: dotnet publish GymManagement.Presentation -c Release -o published
    startCommand: ./published/GymManagement.Presentation
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: gym-db
    databaseName: gymdb
    user: gymuser
    region: frankfurt  # o la región más cercana